[package]
name = "TourBookingSystem"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "*"
prettytable-rs = "*"
lazy_static = "*"